version: '3'

services:
  pg:
    image: postgres:10.0-alpine
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pg_data


  django:
    build: .
    command: bash -c " python manage.py makemigrations && python manage.py migrate && python manage.py crontab add
        && python manage.py loaddata db.json &&  python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - pg
